export const projects = [
  {
    id: 1,
    title: "LearnFlow E-Learning Platform",
    image: "/portfolio/projects/ProjectElearning.png",
    description:
      "A full-stack e-learning platform for RUPP students across multiple majors (ITE, IT, Mathematics), featuring role-based dashboards for students, teachers, and admins.",
    tech: ["React", "Express", "MySQL", "Tailwind CSS", "JWT"],
    category: "Full Stack",
    year: "2026",
    liveUrl: "https://frontend-project-practicum-e-learni.vercel.app/",
    backendUrl: "https://backend-project-practicum-elearning.onrender.com/api",
    githubUrl:
      "https://github.com/nhimdara/Frontend-Project-Practicum-ELearning",
    githubLabel: "Frontend",
    backendGithubUrl:
      "https://github.com/nhimdara/Backend-Project-Practicum-ELearning",
    featured: true,
  },
  {
    id: 2,
    title: "Ecommerce",
    image: "/portfolio/projects/Ecommerce.png",
    description:
      "A modern ecommerce website with product browsing, category filtering, shopping cart features, and a responsive design built using React.js, Tailwind CSS, and Bootstrap.",
    tech: ["React js", "Tailwind", "Bootstrap"],
    category: "Frontend",
    year: "2025",
    liveUrl: "https://computer-shop-murex.vercel.app/",
    githubUrl: "https://github.com/nhimdara/ComputerShop",
    featured: false,
  },
  {
    id: 3,
    title: "Culinary Admin POS",
    image: "/portfolio/projects/CulinaryAdminPOS.png",
    description:
      "A full-stack restaurant management portal with operational dashboards for sales, orders, inventory, tables, products, categories, and payments.",
    tech: ["POS Dashboard", "Admin Portal", "REST API"],
    category: "Full Stack",
    year: "2026",
    liveUrl: "https://mpos-seven.vercel.app/",
    backendUrl: "https://g2-sun-11-mpos-back-gjyx.onrender.com/",
    githubUrl: "https://github.com/NalenSrin123/G2_SUN_11_MPOS",
    featured: true,
  },
  {
    id: 4,
    title: "CineVault Movie Website",
    image: "/portfolio/projects/CineVault.webp",
    description:
      "A responsive movie discovery website with search, genre filters, catalogue sorting, persistent favourites and watchlists, demo authentication, and light and dark themes.",
    tech: ["React 19", "Vite", "Modular CSS"],
    category: "Frontend",
    year: "2026",
    liveUrl: "https://movie-website-wct.vercel.app/",
    githubUrl: "https://github.com/nhimdara/Movie-Website-WCT",
    featured: false,
  },
  {
    id: 5,
    title: "Telegram Shop Mini App",
    image: "/portfolio/projects/TelegramShop.png",
    description:
      "A full-stack Telegram Mini App storefront with verified Telegram authentication, product browsing, user carts, stock-aware orders, and Bakong KHQR and ABA PayWay payment flows.",
    tech: ["React 19", "Telegram SDK", "Laravel 12", "PostgreSQL"],
    category: "Full Stack",
    year: "2026",
    liveUrl: "https://t.me/my_shop67_bot/shop_nw",
    githubUrl: "https://github.com/nhimdara/bot-telegram-test-website",
    githubLabel: "Frontend",
    backendGithubUrl:
      "https://github.com/nhimdara/bot-telegram-test-website-backend",
    featured: true,
  },
  {
    id: 6,
    title: "StayEasy Hotel Booking",
    image: "/portfolio/projects/StayEasyHotel.png",
    description:
      "A full-stack hotel booking platform with destination and date search, wishlists, room reservations, secure payments, and role-based hotel and booking management.",
    tech: ["Vue 3", "Tailwind CSS", "Laravel 10", "Sanctum"],
    category: "Full Stack",
    year: "2026",
    liveUrl: "https://frontend-hotel-booking-ten.vercel.app/",
    backendUrl: "https://backend-hotel-booking-5.onrender.com/api",
    githubUrl: "https://github.com/nhimdara/Frontend_Hotel_Booking",
    githubLabel: "Frontend",
    backendGithubUrl: "https://github.com/nhimdara/Backend_Hotel_Booking",
    featured: true,
  },
  {
    id: 7,
    title: "WOOD'S Cambodia Android App",
    image: "/portfolio/projects/WoodsAndroid.png",
    description:
      "An Android product-catalog application for WOOD'S Cambodia, featuring branded product discovery, responsive navigation, company information, and direct social contact links.",
    tech: ["Android Studio", "React 18", "Capacitor", "Tailwind CSS"],
    category: "Mobile",
    year: "2026",
    liveUrl: null,
    apkUrl:
      "https://raw.githubusercontent.com/nhimdara/my_portfolio69/main/downloads/woods-cambodia.apk",
    githubUrl: "https://github.com/nhimdara/Wood-s",
    featured: true,
  },
  {
    id: 8,
    title: "Library Management API",
    image: "/portfolio/projects/LibraryManagementSwagger.svg",
    description:
      "A Spring Boot REST API for managing books, students, administrators, and borrowing workflows, with MySQL persistence, validation, migrations, and interactive Swagger documentation.",
    tech: ["Spring Boot", "Java 21", "MySQL", "JPA", "Swagger"],
    category: "Backend",
    year: "2026",
    liveUrl: "https://api-production-f2f5.up.railway.app/swagger-ui/index.html",
    githubUrl: "https://github.com/nhimdara/Library_managment_Spring_Boot",
    featured: true,
  },
  {
    id: 9,
    title: "Portfolio Website",
    image: "/portfolio/projects/Portfolio.png",
    description:
      "This personal portfolio site, built to showcase projects, skills, and experience with smooth scroll animations and a responsive layout.",
    tech: ["React", "Tailwind CSS", "Vite"],
    category: "Frontend",
    year: "2026",
    liveUrl: "https://my-portfolio69.vercel.app/",
    githubUrl: "https://github.com/nhimdara/my_portfolio69",
    featured: false,
  },
  {
    id: 10,
    title: "Campus Student Management System",
    image: "/portfolio/projects/StudentManagementSystem.png",
    description:
      "A role-based student information system for managing students, courses, enrollments, scores, GPA calculations, and academic reports through a focused web dashboard and versioned REST API.",
    tech: ["FastAPI", "SQLAlchemy", "Alembic", "Pydantic", "SQLite"],
    category: "Full Stack",
    year: "2026",
    liveUrl: "https://student-management-system-kjf6.onrender.com/",
    githubUrl:
      "https://github.com/nhimdara/Final-Project-DSA-RUPP-ITE-Management-",
    featured: true,
  },
];
